# Generated by Django 5.1.1 on 2024-09-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='bars',
        ),
        migrations.AddField(
            model_name='bar',
            name='dishes',
            field=models.ManyToManyField(through='app_setofshots.BarDish', to='app_setofshots.dish', verbose_name='Позиции меню'),
        ),
    ]
