# Generated by Django 5.1.1 on 2024-09-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0002_remove_dish_bars_bar_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='unique_dish_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='Уникальный идентификатор [Рюмочная_Позиция]'),
        ),
    ]
