# Generated by Django 5.1.1 on 2024-09-24 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0003_alter_dish_unique_dish_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='dishes',
        ),
        migrations.AddField(
            model_name='dish',
            name='bar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='app_setofshots.bar'),
        ),
    ]
