# Generated by Django 5.1.1 on 2024-09-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0004_remove_bar_dishes_dish_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Not started yet', 'Ещё не началось'), ('Already started', 'Уже началось'), ('Ended', 'Закончилось')], max_length=15, verbose_name='Статус'),
        ),
    ]
