# Generated by Django 5.1.1 on 2024-09-24 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0005_event_is_published_alter_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
