# Generated by Django 5.1.1 on 2024-09-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0006_remove_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='events',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Ивенты'),
        ),
    ]
