# Generated by Django 5.1.1 on 2024-09-24 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0007_bar_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='events',
        ),
    ]
