# Generated by Django 5.1.1 on 2024-09-25 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0008_remove_bar_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Ссылка')),
                ('text', models.CharField(max_length=2048, verbose_name='Текст')),
                ('bar', models.ForeignKey(default=None, help_text='Можно оставить пустым, если пост не относится к конкретному бару.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app_setofshots.bar', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
