# Generated by Django 5.1.1 on 2024-09-25 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0009_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bar',
            field=models.ForeignKey(default=None, help_text='Можно оставить пустым, если пост не относится к конкретному бару', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app_setofshots.bar', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Можно оставить пустым', max_length=64, unique=True, verbose_name='Ссылка'),
        ),
    ]
