# Generated by Django 5.1.1 on 2024-09-25 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0011_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bar',
            field=models.ForeignKey(blank=True, default=None, help_text='Можно оставить пустым, если пост не относится к конкретному бару', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app_setofshots.bar', verbose_name='Место'),
        ),
    ]
