# Generated by Django 5.1.1 on 2024-09-25 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0012_alter_post_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bar',
            field=models.ForeignKey(blank=True, help_text='Можно оставить пустым', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app_setofshots.bar', verbose_name='Место'),
        ),
    ]
