# Generated by Django 5.1.1 on 2024-09-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0014_alter_post_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, verbose_name='Опубликовано'),
        ),
    ]
