# Generated by Django 5.1.1 on 2024-09-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0017_alter_post_options_post_pub_date_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Можно оставить пустым', max_length=32, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Можно оставить пустым', max_length=32, unique=True, verbose_name='Ссылка(уникальная)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Можно оставить пустым', max_length=32, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Можно оставить пустым', max_length=128, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, verbose_name='Опубл.'),
        ),
    ]
