# Generated by Django 5.1.1 on 2024-09-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0018_alter_bar_slug_alter_category_slug_alter_dish_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='Можно оставить пустым', max_length=64, unique=True, verbose_name='Ссылка'),
        ),
    ]
