# Generated by Django 5.1.1 on 2024-09-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0020_alter_bar_slug_alter_category_slug_alter_dish_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='image',
            field=models.ImageField(blank=True, upload_to='bars_images', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, upload_to='dishes_images', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='events_images', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts_images', verbose_name='Фото'),
        ),
    ]
