# Generated by Django 5.1.1 on 2024-09-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0021_bar_image_dish_image_event_image_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
