# Generated by Django 5.1.1 on 2024-09-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0024_remove_event_generate_url_remove_event_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Для вставки красивых ссылок(чтобы можно было кликать на слово)\nследует использовать шаблон:\n<a href="ССЫЛКА">КЛИКАБЕЛЬНЫЙ ТЕКСТ</a>. Для удобства:\n\n<a href=""></a>', max_length=1024, verbose_name='Описание'),
        ),
    ]
