# Generated by Django 5.1.1 on 2024-09-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0027_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Для вставки красивых ссылок(чтобы можно было кликать на слово)\nследует использовать шаблон:\n&lt;a href=&quot;ССЫЛКА&quot;&gt;КЛИКАБЕЛЬНЫЙ ТЕКСТ&lt;/a&gt;. Для удобства:\n\n&lt;a href=&quot;&quot;&gt;&lt;/a&gt;', max_length=1024, verbose_name='Описание'),
        ),
    ]
