# Generated by Django 5.1.1 on 2024-09-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0028_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='display_description',
            field=models.TextField(max_length=1024, null=True, verbose_name='Рендер'),
        ),
    ]
