# Generated by Django 5.1.1 on 2024-09-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0030_alter_event_display_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='display_description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Рендер'),
        ),
    ]
