# Generated by Django 5.1.1 on 2024-09-29 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0032_alter_event_display_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='display_description',
        ),
    ]
