# Generated by Django 5.1.1 on 2024-09-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0034_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, verbose_name='Опубликовано'),
        ),
    ]
