# Generated by Django 5.1.1 on 2024-09-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0035_bar_is_published_dish_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, verbose_name='Опубликовано'),
        ),
    ]
