# Generated by Django 5.1.1 on 2024-09-30 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0037_dish_promille'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='unique_dish_id',
        ),
    ]
