# Generated by Django 5.1.1 on 2024-09-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0038_remove_dish_unique_dish_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='slug',
            field=models.SlugField(blank=True, help_text='Заполняется автоматически(если такая ссылка уже существует, стоит добавить постфикс "_<рюмочная>", например: "..._zin"', max_length=32, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
    ]
