# Generated by Django 5.1.1 on 2024-09-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0039_tag_is_published_alter_dish_slug_alter_dish_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_datetime',
            field=models.DateTimeField(auto_created=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
