# Generated by Django 5.1.1 on 2024-10-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0041_alter_bar_description_alter_dish_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='work_time',
            field=models.TextField(max_length=1024, null=True, verbose_name='Часы работы'),
        ),
    ]
