# Generated by Django 5.1.1 on 2024-10-07 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0042_bar_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='bar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='app_setofshots.bar', verbose_name='Рюмочная'),
        ),
    ]
