# Generated by Django 5.1.1 on 2024-10-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0043_alter_dish_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='slug',
            field=models.SlugField(blank=True, help_text='Заполняется автоматически(если такая ссылка уже существует, стоит добавить постфикс "_<рюмочная>", например: "..._zin")', max_length=32, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Для вставки красивых ссылок(чтобы можно было кликать на слово)\nследует использовать шаблон:\n&lt;a href="ССЫЛКА"&gt;КЛИКАБЕЛЬНЫЙ ТЕКСТ&lt;/a&gt;. Для удобства:\n\n&lt;a href=""&gt;&lt;/a&gt;', max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Для вставки красивых ссылок(чтобы можно было кликать на слово)\nследует использовать шаблон:\n<a href="ССЫЛКА">КЛИКАБЕЛЬНЫЙ ТЕКСТ</a>. Для удобства:\n\n<a href=""></a>', max_length=2048, verbose_name='Текст'),
        ),
    ]
