# Generated by Django 5.1.1 on 2024-10-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0045_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Для вставки красивых ссылок(чтобы можно было кликать на слово)<br>следует использовать шаблон:<br>&lt;a href="ССЫЛКА"&gt;КЛИКАБЕЛЬНЫЙ ТЕКСТ&lt;/a&gt;. Шаблон для удобства:<br><br>&lt;a href=""&gt;&lt;/a&gt;', max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Для вставки красивых ссылок(чтобы можно было кликать на слово)<br>следует использовать шаблон:<br>&lt;a href="ССЫЛКА"&gt;КЛИКАБЕЛЬНЫЙ ТЕКСТ&lt;/a&gt;. Шаблон для удобства:<br><br>&lt;a href=""&gt;&lt;/a&gt;', max_length=2048, verbose_name='Текст'),
        ),
    ]
