# Generated by Django 5.1.1 on 2024-10-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0047_alter_post_pub_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, verbose_name='Опубл.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
    ]
