# Generated by Django 5.1.1 on 2024-10-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0048_alter_tag_is_published_alter_tag_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='background_color',
            field=models.CharField(blank=True, help_text='цвет фона должен быть в формате #000000(может быть пустым)', max_length=7, null=True, verbose_name='Цвет фона'),
        ),
    ]
