# Generated by Django 5.1.1 on 2024-10-08 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0049_tag_background_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Underground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Станция')),
                ('image', models.ImageField(blank=True, upload_to='ug_images', verbose_name='Значок')),
            ],
        ),
        migrations.RemoveField(
            model_name='bar',
            name='opening_year',
        ),
        migrations.CreateModel(
            name='BarUnderground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_setofshots.bar')),
                ('underground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_setofshots.underground')),
            ],
        ),
        migrations.AddField(
            model_name='bar',
            name='underground',
            field=models.ManyToManyField(through='app_setofshots.BarUnderground', to='app_setofshots.underground', verbose_name='Метро'),
        ),
    ]
