# Generated by Django 5.1.1 on 2024-10-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0050_underground_remove_bar_opening_year_barunderground_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='underground',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, verbose_name='Опубл.'),
        ),
    ]
