# Generated by Django 5.1.1 on 2024-10-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0051_underground_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='underground',
            options={'verbose_name': 'метро', 'verbose_name_plural': 'Метро'},
        ),
    ]
