# Generated by Django 5.1.1 on 2024-10-08 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0052_alter_underground_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='work_time',
        ),
        migrations.AddField(
            model_name='bar',
            name='instagram_link',
            field=models.CharField(blank=True, help_text='можно оставить пустым', max_length=100, null=True, verbose_name='Ссылка на инстаграм'),
        ),
        migrations.AddField(
            model_name='bar',
            name='telegram_link',
            field=models.CharField(blank=True, help_text='можно оставить пустым', max_length=100, null=True, verbose_name='Ссылка на тг-канал'),
        ),
        migrations.AddField(
            model_name='bar',
            name='work_time_friday',
            field=models.CharField(max_length=11, null=True, verbose_name='Часы работы(пт)'),
        ),
        migrations.AddField(
            model_name='bar',
            name='work_time_monday',
            field=models.CharField(max_length=11, null=True, verbose_name='Часы работы(пн)'),
        ),
        migrations.AddField(
            model_name='bar',
            name='work_time_saturday',
            field=models.CharField(max_length=11, null=True, verbose_name='Часы работы(сб)'),
        ),
        migrations.AddField(
            model_name='bar',
            name='work_time_sunday',
            field=models.CharField(max_length=11, null=True, verbose_name='Часы работы(вс)'),
        ),
        migrations.AddField(
            model_name='bar',
            name='work_time_thursday',
            field=models.CharField(max_length=11, null=True, verbose_name='Часы работы(чт)'),
        ),
        migrations.AddField(
            model_name='bar',
            name='work_time_tuesday',
            field=models.CharField(max_length=11, null=True, verbose_name='Часы работы(вт)'),
        ),
        migrations.AddField(
            model_name='bar',
            name='work_time_wednesday',
            field=models.CharField(max_length=11, null=True, verbose_name='Часы работы(ср)'),
        ),
        migrations.AddField(
            model_name='bar',
            name='yandex_maps_link',
            field=models.CharField(blank=True, help_text='Лучше оставить пустым', max_length=2048, null=True, verbose_name='Ссылка на карты'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='image',
            field=models.ImageField(blank=True, upload_to='bars_images', verbose_name='Главное Фото'),
        ),
        migrations.CreateModel(
            name='AttachmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='attachment_images', verbose_name='Фото для карусели')),
                ('is_published', models.BooleanField(blank=True, default=False, verbose_name='Опубликовано')),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_image', to='app_setofshots.bar', verbose_name='Рюмочная')),
            ],
            options={
                'verbose_name': 'фото для карусели',
                'verbose_name_plural': 'Фото для карусели',
            },
        ),
    ]
