# Generated by Django 5.1.1 on 2024-10-08 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0053_remove_bar_work_time_bar_instagram_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentimage',
            name='bar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_image', to='app_setofshots.bar', verbose_name='Рюмочная'),
        ),
    ]
