# Generated by Django 5.1.1 on 2024-10-08 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0054_alter_attachmentimage_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentimage',
            name='bar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_image', to='app_setofshots.bar', verbose_name='Рюмочная'),
            preserve_default=False,
        ),
    ]
