# Generated by Django 5.1.1 on 2024-10-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0055_alter_attachmentimage_bar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
