# Generated by Django 5.1.1 on 2024-10-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0056_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'ивент', 'verbose_name_plural': 'Ивенты'},
        ),
    ]
