# Generated by Django 5.1.1 on 2024-10-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0057_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(blank=True, help_text='По умолчанию 3 часа', null=True, verbose_name='Длительность в часах'),
        ),
    ]
