# Generated by Django 5.1.1 on 2024-10-19 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0058_event_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
                ('day', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='attachmentimage',
            name='bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_images', to='app_setofshots.bar', verbose_name='Рюмочная'),
        ),
        migrations.AlterField(
            model_name='attachmentimage',
            name='image',
            field=models.ImageField(default=123, upload_to='attachment_images', verbose_name='Фото для карусели'),
            preserve_default=False,
        ),
    ]
