# Generated by Django 5.1.1 on 2024-10-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setofshots', '0059_logs_alter_attachmentimage_bar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_drink',
            field=models.BooleanField(default=False, help_text='Если напиток- поставить галочку', verbose_name='Это напиток'),
        ),
    ]
